import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import Layout from '../../components/shared/Layout';
import { useAuth } from '../../context/AuthContext';
import { bookingApi, guideApi, notificationApi } from '../../lib/api';
import { MapPin, Star, Calendar, Clock, TrendingUp, Award, Compass, Users, Film } from 'lucide-react';
import { format } from 'date-fns';

export default function TravelerDashboard() {
  const { user } = useAuth();
  const [bookings, setBookings] = useState([]);
  const [guides, setGuides] = useState([]);
  const [notifications, setNotifications] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      bookingApi.getMyBookings({ role: 'traveler' }).catch(() => ({ bookings: [] })),
      guideApi.search({ limit: 6 }).catch(() => ({ guides: [] })),
      notificationApi.getAll().catch(() => ({ notifications: [] })),
    ]).then(([b, g, n]) => {
      setBookings(b.bookings || []);
      setGuides(g.guides || []);
      setNotifications(n.notifications?.slice(0, 5) || []);
      setLoading(false);
    });
  }, []);

  const upcomingBookings = bookings.filter(b => ['PENDING', 'CONFIRMED'].includes(b.status));
  const [cancellingId, setCancellingId] = useState(null);
  const [showCancelConfirm, setShowCancelConfirm] = useState(null);

  const handleCancel = async (bookingId) => {
    setCancellingId(bookingId);
    try {
      await bookingApi.cancel(bookingId);
      setBookings(bs => bs.map(b => b.id === bookingId ? { ...b, status: 'CANCELLED' } : b));
      toast.success('Booking cancelled', 'Refund added to your wallet if applicable');
    } catch (err) { toast.error(err.message); }
    finally { setCancellingId(null); setShowCancelConfirm(null); }
  };

  const downloadItinerary = (b) => {
    const guideName = b.guide?.fullName || 'Your Guide';
    const content = `<html><head><title>LocalLens Itinerary</title><style>body{font-family:Arial,sans-serif;padding:40px;color:#111}.header{background:#22c55e;color:white;padding:20px;border-radius:8px;margin-bottom:24px}.header h1{margin:0;font-size:24px}.section{margin-bottom:20px}.section h3{color:#16a34a;border-bottom:1px solid #e5e7eb;padding-bottom:6px}.row{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #f3f4f6}.label{color:#6b7280;font-size:13px}.value{font-weight:600;font-size:13px}.footer{margin-top:40px;text-align:center;color:#9ca3af;font-size:12px}</style></head><body><div class="header"><h1>🌍 LocalLens Tour Itinerary</h1><p>Booking confirmed — have a great trip!</p></div><div class="section"><h3>Booking Details</h3><div class="row"><span class="label">Booking ID</span><span class="value">#${b.id.slice(0,8).toUpperCase()}</span></div><div class="row"><span class="label">Tour Date</span><span class="value">${new Date(b.date).toDateString()}</span></div><div class="row"><span class="label">Start Time</span><span class="value">${b.startTime||'TBD'}</span></div><div class="row"><span class="label">Duration</span><span class="value">${(b.duration||'').replace(/_/g,' ')}</span></div></div><div class="section"><h3>Guide Information</h3><div class="row"><span class="label">Guide Name</span><span class="value">${guideName}</span></div></div><div class="section"><h3>Meetup Details</h3><div class="row"><span class="label">Meetup Point</span><span class="value">${b.meetupLocation||'To be confirmed'}</span></div><div class="row"><span class="label">People</span><span class="value">${b.numberOfPeople||1}</span></div></div><div class="section"><h3>Payment Summary</h3><div class="row"><span class="label">Total</span><span class="value">₹${b.totalAmount}</span></div><div class="row"><span class="label">Status</span><span class="value">${b.paymentStatus||'PENDING'}</span></div></div><div class="footer">Generated by LocalLens • Have a wonderful journey! 🌏</div></body></html>`;
    const win = window.open('', '_blank');
    if (win) { win.document.write(content); win.document.close(); win.print(); }
  };

  const handleSOS = (b) => {
    if (!navigator.geolocation) { toast.error('Geolocation not supported'); return; }
    navigator.geolocation.getCurrentPosition(async (pos) => {
      try {
        await import('../../lib/api').then(({ api }) => api.post('/sos', { latitude: pos.coords.latitude, longitude: pos.coords.longitude, bookingId: b.id, message: 'Traveler triggered SOS alert' }));
        toast.error('SOS Sent! 🆘', 'Your guide has been alerted. Stay safe.');
      } catch { toast.error('SOS failed', 'Please call emergency services directly'); }
    }, () => toast.error('Location required for SOS'));
  };
  const completedBookings = bookings.filter(b => b.status === 'COMPLETED');

  if (loading) return <Layout><div className="text-center py-20"><div className="animate-spin w-8 h-8 border-4 border-green-500 border-t-transparent rounded-full mx-auto"/></div></Layout>;

  return (
    <Layout>
      {/* Welcome Banner */}
      <div className="bg-gradient-to-r from-green-600 to-emerald-500 rounded-2xl p-6 text-white mb-6">
        <h1 className="text-2xl font-bold mb-1">Welcome back, {user?.fullName?.split(' ')[0]}! 👋</h1>
        <p className="text-green-100 text-sm">Discover local guides and hidden gems around the world</p>
        <div className="flex gap-3 mt-4">
          <Link to="/explore" className="bg-white text-green-700 px-4 py-2 rounded-lg text-sm font-semibold hover:bg-green-50 transition">
            Explore Guides
          </Link>
          <Link to="/map" className="bg-green-500 border border-white/30 text-white px-4 py-2 rounded-lg text-sm font-semibold hover:bg-green-400 transition">
            View Map
          </Link>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {[
          { label: 'Total Bookings', value: bookings.length, icon: Calendar, color: 'text-blue-600 bg-blue-50' },
          { label: 'Completed Tours', value: completedBookings.length, icon: Award, color: 'text-green-600 bg-green-50' },
          { label: 'Upcoming', value: upcomingBookings.length, icon: Clock, color: 'text-orange-600 bg-orange-50' },
          { label: 'Loyalty Points', value: (user?.travelerProfile?.loyaltyPoints || 0), icon: TrendingUp, color: 'text-purple-600 bg-purple-50' },
        ].map(stat => (
          <div key={stat.label} className="card p-4">
            <div className={`w-9 h-9 rounded-xl flex items-center justify-center ${stat.color} mb-3`}>
              <stat.icon className="w-5 h-5" />
            </div>
            <p className="text-2xl font-bold text-gray-900">{stat.value}</p>
            <p className="text-xs text-gray-500 mt-0.5">{stat.label}</p>
          </div>
        ))}
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        {/* Quick Links */}
        <div className="md:col-span-1">
          <h2 className="font-bold text-gray-900 mb-3">Quick Actions</h2>
          <div className="space-y-2">
            {[
              { to: '/explore', icon: Compass, label: 'Find Guides', desc: 'Browse local experts', color: 'text-green-600' },
              { to: '/group-tours', icon: Users, label: 'Group Tours', desc: 'Join group experiences', color: 'text-blue-600' },
              { to: '/reels', icon: Film, label: 'Travel Reels', desc: 'Watch & share videos', color: 'text-pink-600' },
              { to: '/map', icon: MapPin, label: 'Live Map', desc: 'See guides near you', color: 'text-orange-600' },
            ].map(item => (
              <Link key={item.to} to={item.to} className="card p-3 flex items-center gap-3 hover:shadow-md transition group">
                <div className="w-9 h-9 rounded-xl bg-gray-50 flex items-center justify-center group-hover:scale-110 transition">
                  <item.icon className={`w-5 h-5 ${item.color}`} />
                </div>
                <div>
                  <p className="font-medium text-sm text-gray-900">{item.label}</p>
                  <p className="text-xs text-gray-500">{item.desc}</p>
                </div>
              </Link>
            ))}
          </div>
        </div>

        {/* Upcoming Bookings */}
        <div className="md:col-span-1">
          <div className="flex items-center justify-between mb-3">
            <h2 className="font-bold text-gray-900">Upcoming Tours</h2>
            <Link to="/messages" className="text-xs text-green-600 hover:underline">View all</Link>
          </div>
          {upcomingBookings.length === 0 ? (
            <div className="card p-6 text-center text-gray-500">
              <Calendar className="w-8 h-8 mx-auto mb-2 text-gray-300" />
              <p className="text-sm">No upcoming tours</p>
              <Link to="/explore" className="text-green-600 text-sm hover:underline mt-1 block">Book one now →</Link>
            </div>
          ) : (
            <div className="space-y-2">
              {upcomingBookings.slice(0, 4).map(b => (
                <div key={b.id} className="card p-3">
                  <div className="flex items-center justify-between mb-1">
                    <div className="flex items-center gap-2">
                      {b.guide?.avatarUrl ? (
                        <img src={b.guide.avatarUrl} className="w-7 h-7 rounded-full object-cover" alt="" />
                      ) : (
                        <div className="w-7 h-7 rounded-full bg-green-200 flex items-center justify-center text-xs font-bold text-green-700">
                          {b.guide?.fullName?.[0]}
                        </div>
                      )}
                      <span className="text-sm font-medium text-gray-900">{b.guide?.fullName}</span>
                    </div>
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                      b.status === 'CONFIRMED' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'
                    }`}>{b.status}</span>
                  </div>
                  <p className="text-xs text-gray-500">
                    {format(new Date(b.date), 'MMM d, yyyy')} • {b.startTime} • {b.duration.replace(/_/g, ' ')}
                  </p>
                  <p className="text-xs text-gray-500">₹{b.totalAmount?.toFixed(0)}</p>
                  <div className="flex gap-1.5 mt-2 flex-wrap">
                    {b.status === 'CONFIRMED' && (
                      <button onClick={() => downloadItinerary(b)} className="text-xs px-2 py-1 border border-gray-200 rounded-lg text-gray-600 hover:bg-gray-50 transition">📄 Itinerary</button>
                    )}
                    {['PENDING','CONFIRMED'].includes(b.status) && (
                      showCancelConfirm === b.id ? (
                        <div className="flex gap-1">
                          <button onClick={() => handleCancel(b.id)} disabled={cancellingId === b.id} className="text-xs px-2 py-1 bg-red-600 text-white rounded-lg hover:bg-red-700 transition">
                            {cancellingId === b.id ? '...' : 'Yes, Cancel'}
                          </button>
                          <button onClick={() => setShowCancelConfirm(null)} className="text-xs px-2 py-1 bg-gray-100 text-gray-600 rounded-lg">Keep</button>
                        </div>
                      ) : (
                        <button onClick={() => setShowCancelConfirm(b.id)} className="text-xs px-2 py-1 border border-red-200 text-red-600 rounded-lg hover:bg-red-50 transition">Cancel</button>
                      )
                    )}
                    {b.status === 'CONFIRMED' && new Date(b.date).toDateString() === new Date().toDateString() && (
                      <button onClick={() => handleSOS(b)} className="text-xs px-2 py-1 bg-red-600 text-white rounded-lg font-bold hover:bg-red-700 transition">🆘 SOS</button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Notifications */}
        <div className="md:col-span-1">
          <div className="flex items-center justify-between mb-3">
            <h2 className="font-bold text-gray-900">Notifications</h2>
            <Link to="/notifications" className="text-xs text-green-600 hover:underline">View all</Link>
          </div>
          {notifications.length === 0 ? (
            <div className="card p-6 text-center text-gray-500">
              <p className="text-sm">No new notifications</p>
            </div>
          ) : (
            <div className="space-y-2">
              {notifications.map(n => (
                <div key={n.id} className={`card p-3 ${!n.isRead ? 'border-l-4 border-l-green-500' : ''}`}>
                  <p className="text-sm font-medium text-gray-900">{n.title}</p>
                  <p className="text-xs text-gray-500 mt-0.5">{n.body}</p>
                  <p className="text-xs text-gray-400 mt-1">{format(new Date(n.createdAt), 'MMM d, h:mm a')}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Featured Guides */}
      {guides.length > 0 && (
        <div className="mt-6">
          <div className="flex items-center justify-between mb-3">
            <h2 className="font-bold text-gray-900">Featured Guides</h2>
            <Link to="/explore" className="text-xs text-green-600 hover:underline">See all</Link>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {guides.slice(0, 6).map(g => (
              <Link key={g.id} to={`/guides/${g.id}`} className="card p-4 hover:shadow-md transition">
                <div className="flex items-center gap-3 mb-2">
                  {g.user?.avatarUrl ? (
                    <img src={g.user.avatarUrl} className="w-10 h-10 rounded-full object-cover" alt="" />
                  ) : (
                    <div className="w-10 h-10 rounded-full bg-green-200 flex items-center justify-center text-sm font-bold text-green-700">
                      {g.user?.fullName?.[0]}
                    </div>
                  )}
                  <div>
                    <p className="font-medium text-sm text-gray-900 line-clamp-1">{g.user?.fullName}</p>
                    <p className="text-xs text-gray-500 flex items-center gap-1">
                      <MapPin className="w-3 h-3" />{g.city}
                    </p>
                  </div>
                </div>
                <div className="flex items-center justify-between text-xs">
                  <span className="flex items-center gap-1 text-yellow-600">
                    <Star className="w-3 h-3 fill-current" /> {g.avgRating?.toFixed(1) || '0.0'}
                  </span>
                  <span className="text-green-600 font-medium">₹{g.hourlyRate}/hr</span>
                </div>
                {g.expertiseTags?.slice(0, 2).map(tag => (
                  <span key={tag} className="inline-block text-xs bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full mt-1 mr-1">{tag}</span>
                ))}
              </Link>
            ))}
          </div>
        </div>
      )}
    </Layout>
  );
}
